### PR TITLE
Preinstalled python

### PR DESCRIPTION
**Pull request by ondrajodas**
Solving - https://keboola.atlassian.net/browse/COM-48

### CODE REVIEW

**Review by pivnicek — CHANGES_REQUESTED** [review]
@ondrajodas huh?  Please see line #1 :-)  This begins with the python docker image.

I thought the issue was that they wanted to include https://github.com/keboola/sapi-python-client ?

**Comment by ondrajodas** [comment]
věděl jsem že to nebude tak jednoduché :D

**Comment by pivnicek** [comment]
:-) Here's a hint https://github.com/keboola/docker-jupyter/blob/master/Dockerfile#L139

**Comment by ondrajodas** [comment]
@pivnicek ok and what now? :)

**Comment by pivnicek** [comment]
I think that's it.  I'm not convinced that it's a good idea to do this though (see my comment here https://keboola.atlassian.net/browse/COM-48?focusedCommentId=11282) .  So let's put it on hold for now maybe.

**Comment by pivnicek** [comment]
closed as won't do.

**Pull request closed without merging**
