### PR TITLE
fixed typo in previous PR

### PR DESCRIPTION
**Pull request by pocin**
sry for confusion, still quite new to make PRs

------
Previously installing requests did not work because of
```
[root@48790cd home]# pip install requests
Collecting requests
  Could not fetch URL https://pypi.python.org/simple/requests/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645) - skipping
  Could not find a version that satisfies the requirement requests (from versions: )
No matching distribution found for requests
```

this should fix the issue
http://stackoverflow.com/a/40213220/4050925

### CODE REVIEW

**Comment by odinuv** [comment]
Hi,
I don't see the problem here. Installing package `requests` works because "Requirement already satisfied". Also installing other packages from pypi.python.org works. pypi.python.org has a valid certificate and uses a secure connection. Adding it to trusted hosts seems unnecessary to me and it will also circumvent the HTTPS check. What is the exact issue you're having?

**Comment by pocin** [comment]
EDIT:
there is quite a lengthy issue in docker-compose gh https://github.com/docker/compose/issues/890 
I did not have time to skim through yet, but it might be related to my computer setup only. 
WIll debug tomorow, and let you know.


Hi, that's strange.. 
I just can not `import requests` in my vanilla container.
This is the most simple example failing:
`./docker-compose.yml`
```
version: "2"
services:
  test-requests:
    image: quay.io/keboola/docker-custom-python:1.1.2
    tty: true
    stdin_open: true
    command: python -c 'import requests'
    volumes:
      - ./:/src/
```
 Run with `$docker-compose run --rm -e KBC_DATADIR=/src/tests/data/ test-requests`

Strangely enough when I invoke bash in my image and do
`[root@asdfczxvzcx home]# find / -name requests`

they are found inside folder: `/usr/local/lib/python3.5/site-packages/pip/_vendor/requests` 

What is even more strange - it seems that all remaining packages are installed:
```
[root@60704062038e home]# pip list
backports.shutil-get-terminal-size (1.0.0)
cycler (0.10.0)
decorator (4.0.9)
flake8 (2.5.4)
httplib2 (0.9.2)
ipython (4.2.0)
ipython-genutils (0.1.0)
Keboola (1.0)
matplotlib (1.5.1)
mccabe (0.4.0)
numpy (1.11.0)
pandas (0.18.0)
pep8 (1.7.0)
pexpect (4.0.1)
pickleshare (0.7.2)
pip (8.0.1)
ptyprocess (0.5.1)
py (1.4.31)
pyflakes (1.0.0)
pymongo (3.2.2)
pyparsing (2.1.1)
pytest (2.9.1)
python-dateutil (2.5.3)
pytz (2016.4)
PyYAML (3.11)
setuptools (18.2)
simplegeneric (0.8.1)
six (1.10.0)
traitlets (4.2.1)
```

**Comment by odinuv** [comment]
Is there any particular reason for the `1.1.2` tag? That is a year old version - the current one is 1.2.5
And the compose file works fine the 1.2.5 version.

**Comment by pocin** [comment]
copied that one from the dev docs https://developers.keboola.com/extend/custom-science/python/

after pulling the latest image (1.2.5) it works. Thanks for your help!

**Comment by odinuv** [comment]
Ah! Sorry about that, I'll update the docs immediately.

**Pull request closed without merging**
