### PR TITLE
PS-841 update to py 3.8.5

### PR DESCRIPTION
**Pull request by pivnicek**

### CODE REVIEW

**Review by JakubMatejka — APPROVED** [review]
ok (btw. should we hardcode it to the patch version? Probably yes as we have to rebuild it anyway, right? 🤔)

**Comment by pivnicek** [comment]
not sure what you mean, hard-code what to which patch version? :-)

**Comment by JakubMatejka** [comment]
Sorry 🤭 I meant if we could put there just `FROM python:3.8` and let it be patched "automatically" without need of changes in the code. But in that case we would need to run the release (and so rebuild of the image) manually anyway so it would not probably give a lot of advantage.

**Comment by pivnicek** [comment]
Ah, I see.  yes.  Another thing is that even the minor releases can break various packages or whatnot,  it's not very reliable.  So fixing the version is I think the best, because then you also have it clear which build is running which exact version.

**Comment by JakubMatejka** [comment]
Oh, right. Ok, no more questions. 😄

**Pull request merged**
